'use strict';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const KEY='online-notepad-side-panel-v1',colors={blue:['#6093eb','#edf4ff'],yellow:['#e6b943','#fff9df'],green:['#64b69b','#ecf8f0'],pink:['#dd87a8','#fff0f5'],purple:['#aa8de3','#f3efff'],white:['#a9b5c9','#ffffff']};
const fonts={sans:'system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',serif:'Georgia, "Times New Roman", serif',mono:'"SFMono-Regular", Consolas, "Liberation Mono", monospace'};
const extensions={plain:'txt',rich:'html',sql:'sql',javascript:'js',typescript:'ts',python:'py',json:'json',html:'html',css:'css',markdown:'md',shell:'sh'};
let state,filter='all',view='editor',zoom=1,toastTimer,saveTimer,activeHistory=new Map(),restoring=false,storageOK=true;
const uid=()=>globalThis.crypto?.randomUUID?.()||Date.now().toString(36)+Math.random().toString(36).slice(2);
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function makeNote(title='Untitled note',content='',language='plain',color='blue'){return{id:uid(),title,content,language,color,font:language==='plain'?'sans':'mono',size:16,textColor:'#24324b',created:Date.now(),updated:Date.now(),pinned:false,deleted:false,x:30+Math.random()*450,y:30+Math.random()*250,width:270,height:245,rich:''};}
function initial(){const notes=[makeNote('A fresh page','A little space to think clearly.\n\nKeep your ideas, working queries, and everyday notes together. Everything you write stays in this browser.\n\nA few things to try\n\n• Create a note with the blue + New note button.\n• Switch to Board for a collection of sticky notes.\n• Arrange your thoughts freely on the Canvas.\n• Choose SQL or another language for colorful code.\n• Download a note, or back up your entire workspace.\n\nMake this space your own.','plain','blue'),makeNote('My query scratchpad','-- Your next query starts here\nSELECT\n    customer_id,\n    customer_name,\n    order_total\nFROM customer_orders\nWHERE order_status = \'Released\'\nORDER BY order_total DESC;','sql','purple'),makeNote('Little things to remember','☐ Capture the idea before it disappears\n☐ Review today’s queries\n☐ Export a backup on Friday','plain','yellow')];notes.forEach((n,i)=>{n.x=35+i*310;n.y=45+(i%2)*90});return{version:1,notes,active:notes[0].id,settings:{motion:!matchMedia('(prefers-reduced-motion: reduce)').matches,spellcheck:true,wrap:true,background:'dots'}};}
try{const data=localStorage.getItem(KEY);state=data?JSON.parse(data):initial();if(!state||!Array.isArray(state.notes)||!state.settings)throw Error('Invalid workspace');}catch(e){state=initial();storageOK=false;setTimeout(()=>toast('Could not load browser storage. Export a backup before closing.'),300);}
function current(){return state.notes.find(n=>n.id===state.active&&!n.deleted);}
function toast(t){$('#toast').textContent=t;$('#toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('show'),3600);}
function save(){clearTimeout(saveTimer);try{localStorage.setItem(KEY,JSON.stringify(state));storageOK=true;$('#saveStatus').textContent='Saved on device';}catch(e){storageOK=false;$('#saveStatus').textContent='Save failed — download backup';toast('Browser storage is full or unavailable. Download a backup now.');}}
function scheduleSave(){ $('#saveStatus').textContent='Saving…'; clearTimeout(saveTimer);saveTimer=setTimeout(save,180);}
function filtered(){const q=$('#search').value.toLowerCase();return state.notes.filter(n=>(filter==='trash'?n.deleted:!n.deleted&&(filter!=='pinned'||n.pinned))&&(!q||(n.title+' '+n.content).toLowerCase().includes(q))).sort((a,b)=>{const sort=$('#sort').value;return sort==='title'?a.title.localeCompare(b.title):sort==='created'?b.created-a.created:(Number(b.pinned)-Number(a.pinned)||b.updated-a.updated)});}
function shortDate(n){return new Date(n.updated).toLocaleDateString(undefined,{month:'short',day:'numeric'});}
function renderList(){const notes=filtered();$('#allCount').textContent=state.notes.filter(n=>!n.deleted).length;$('#pinCount').textContent=state.notes.filter(n=>!n.deleted&&n.pinned).length;$('#trashCount').textContent=state.notes.filter(n=>n.deleted).length;$('#noteCount').textContent=notes.length;$('#noteList').innerHTML=notes.map(n=>`<button class="list-note ${n.id===state.active?'active':''}" data-note="${n.id}" style="--card-color:${colors[n.color][0]}"><span class="note-marker"></span><span><strong>${esc(n.title||'Untitled note')}</strong><small>${n.pinned?'☆ · ':''}${shortDate(n)} · ${esc(n.language==='plain'?'Text':n.language.toUpperCase())}</small></span></button>`).join('')||'<p class="hint" style="padding:10px">No notes here yet.</p>';}
function renderBoard(){const notes=filtered();$('#boardInfo').textContent=`${notes.length} ${notes.length===1?'note':'notes'}${view==='canvas'?' · Drag a card by its header · Resize from its corner':''}`;$('#board').innerHTML=notes.map((n,i)=>`<article class="note-card" data-id="${n.id}" style="--card-bg:${colors[n.color][1]};--card-color:${colors[n.color][0]};animation-delay:${Math.min(i,10)*25}ms;${view==='canvas'?`left:${n.x}px;top:${n.y}px;width:${n.width||270}px;height:${n.height||245}px`:''}"><div class="card-top"><span>▤ ${esc(n.language==='plain'?'Note':n.language)}</span><button data-pin="${n.id}" aria-label="${n.pinned?'Unpin':'Pin'} ${esc(n.title)}">${n.pinned?'★':'☆'}</button></div><h3>${esc(n.title||'Untitled note')}</h3><div class="card-body">${esc(n.content||'An empty page, full of possibility.')}</div><div class="card-bottom"><span>${shortDate(n)}</span><button data-open="${n.id}">${n.deleted?'Restore':'Open ↗'}</button></div></article>`).join('')+(filter!=='trash'?'<button class="add-card" id="boardNew"><span>＋</span>Create a new note</button>':'');if(!notes.length&&filter==='trash')$('#board').innerHTML='<div class="empty"><h3>Trash is empty</h3><p>Deleted notes stay here until you remove them permanently.</p></div>';$('#boardNew')?.addEventListener('click',newNote);if(view==='canvas')setupDrag();}
function render(){renderList();if(view!=='editor')renderBoard();}
function setView(v){view=v;$('#editorView').hidden=v!=='editor';$('#boardView').hidden=v==='editor';$$('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===v));$('#boardView').classList.toggle('canvas-mode',v==='canvas');['zoomIn','zoomOut','zoomLevel','resetCanvas'].forEach(id=>$('#'+id).hidden=v!=='canvas');$('#board').style.transform=v==='canvas'?`scale(${zoom})`:'';if(v==='editor')loadEditor();else renderBoard();}
function choose(id){const n=state.notes.find(x=>x.id===id);if(n?.deleted){showTrash(n);return;}state.active=id;setView('editor');renderList();save();}
function newNote(){const n=makeNote();state.notes.unshift(n);state.active=n.id;filter='all';setFilter('all');setView('editor');save();$('#title').focus();$('#title').select();}
function setFilter(f){filter=f;$$('[data-filter]').forEach(b=>b.classList.toggle('active',b.dataset.filter===f));$('#workspaceName').textContent=f==='all'?'All notes':f==='pinned'?'Pinned':'Trash';$('#heading').textContent=f==='all'?'Your notes, beautifully simple.':f==='pinned'?'Keep the important things close.':'A second chance for your notes.';$('#subheading').textContent=f==='all'?'Thoughts, queries, and everything in between.':f==='pinned'?'Your favorite ideas, always within reach.':'Restore a note or remove it permanently.';if(f!=='all')setView('board');render();}
function loadEditor(){const n=current();if(!n){setView('board');return;}$('#title').value=n.title;$('#editor').value=n.content;$('#richEditor').innerHTML=sanitize(n.rich||esc(n.content).replace(/\n/g,'<br>'));$('#language').value=n.language;$('#font').value=n.font;$('#fontSize').value=String(n.size);$('#textColor').value=n.textColor;$('#noteDot').style.background=colors[n.color][0];$('#pinNote').textContent=n.pinned?'★':'☆';$('#pinNote').style.color=n.pinned?'#d9a82e':'';applyEditorSettings();highlight();stats();}
function applyEditorSettings(){const n=current();if(!n)return;const rich=n.language==='rich',code=!['plain','rich'].includes(n.language);$('#editor').hidden=rich;$('#richEditor').hidden=!rich;$('#writingArea').classList.toggle('code-mode',code);$('#writingArea').classList.toggle('no-wrap',!state.settings.wrap);document.documentElement.style.setProperty('--note-font',fonts[n.font]);document.documentElement.style.setProperty('--note-size',n.size+'px');document.documentElement.style.setProperty('--text-color',n.textColor);$('#editor').spellcheck=state.settings.spellcheck&&!code;$('#richEditor').spellcheck=state.settings.spellcheck;$('#wrapButton').classList.toggle('active',state.settings.wrap);$('#languageLabel').textContent=$('#language').selectedOptions[0]?.textContent||'Plain text';document.body.classList.toggle('no-motion',!state.settings.motion);$('#ambient').style.display=state.settings.motion?'':'none';document.body.dataset.background=state.settings.background;}
function highlight(){const n=current();if(!n)return;const text=n.content;$('#gutter').textContent=Array.from({length:Math.min(text.split('\n').length,30000)},(_,i)=>i+1).join('\n');if(['plain','rich'].includes(n.language))return;if(text.length>250000){$('#highlight').textContent=text+'\n';syncScroll();return;}const re=/(\/\*[\s\S]*?\*\/|\/\/[^\n]*|--[^\n]*|#[^\n]*|"(?:\\.|[^"\\])*"|'(?:\\.|[^'\\])*'|`(?:\\.|[^`\\])*`|\b(?:SELECT|FROM|WHERE|AND|OR|NOT|AS|JOIN|LEFT|RIGHT|INNER|OUTER|ON|ORDER|BY|GROUP|HAVING|LIMIT|INSERT|INTO|VALUES|UPDATE|SET|DELETE|CREATE|TABLE|DROP|ALTER|DISTINCT|DESC|ASC|NULL|IS|CASE|WHEN|THEN|ELSE|END|WITH|UNION|ALL|EXISTS|IN|LIKE|BETWEEN|const|let|var|function|return|if|else|for|while|class|new|import|export|default|async|await|try|catch|throw|true|false|undefined|def|elif|None|True|False|in|is|print|self|pass|break|continue|yield|public|private|interface|type|extends)\b|\b\d+(?:\.\d+)?\b|\b[A-Za-z_]\w*(?=\s*\())/gi;let html='',last=0;for(const m of text.matchAll(re)){const t=m[0];const cls=/^(\/\/|\/\*|--|#)/.test(t)?'comment':/^['"`]/.test(t)?'string':/^\d/.test(t)?'number':/^[A-Za-z_]\w*$/.test(t)&&text.slice(m.index+t.length).match(/^\s*\(/)?'function':'keyword';html+=esc(text.slice(last,m.index))+`<span class="tok-${cls}">${esc(t)}</span>`;last=m.index+t.length;}$('#highlight').innerHTML=html+esc(text.slice(last))+'\n';syncScroll();}
function stats(){const n=current();if(!n)return;const text=n.content;$('#stats').textContent=`${text.trim()?text.trim().split(/\s+/u).length:0} words · ${Array.from(text).length.toLocaleString()} characters`;const el=$('#editor'),pos=el.selectionStart;$('#selectionInfo').textContent=n.language==='rich'?'':`Ln ${text.slice(0,pos).split('\n').length}, Col ${pos-(text.lastIndexOf('\n',pos-1)+1)+1}${el.selectionEnd-pos?' · '+(el.selectionEnd-pos)+' selected':''}`;}
function syncScroll(){$('#highlight').scrollTop=$('#editor').scrollTop;$('#highlight').scrollLeft=$('#editor').scrollLeft;$('#gutter').scrollTop=$('#editor').scrollTop;}
function snapshot(){const n=current();if(!n||restoring)return;let h=activeHistory.get(n.id);if(!h){h={past:[],future:[]};activeHistory.set(n.id,h);}h.past.push({content:n.content,rich:n.rich});while(h.past.length>100||h.past.reduce((a,v)=>a+v.content.length+(v.rich||'').length,0)>8e6)h.past.shift();h.future=[];}
function changed(){const n=current();if(!n)return;snapshot();if(n.language==='rich'){n.rich=sanitize($('#richEditor').innerHTML);n.content=$('#richEditor').innerText;}else{n.content=$('#editor').value;n.rich='';}n.updated=Date.now();highlight();stats();scheduleSave();if(state.settings.motion){$('#editorView').classList.remove('typing-glow');requestAnimationFrame(()=>$('#editorView').classList.add('typing-glow'));}updateFindCount();}
function historyMove(redo=false){const n=current(),h=activeHistory.get(n?.id);if(!h)return;const from=redo?h.future:h.past,to=redo?h.past:h.future;if(!from.length)return;to.push({content:n.content,rich:n.rich});Object.assign(n,from.pop());n.updated=Date.now();loadEditor();save();}
function sanitize(html){const template=document.createElement('template');template.innerHTML=html;const allowed=new Set(['B','STRONG','I','EM','U','S','STRIKE','BR','P','DIV','SPAN','FONT','UL','OL','LI','BLOCKQUOTE','PRE','CODE','H1','H2','H3']);const walk=node=>{for(const child of [...node.children]){if(!allowed.has(child.tagName)){child.replaceWith(document.createTextNode(child.textContent));continue;}const color=child.getAttribute('color'),style=child.style;const safe={color:style.color,backgroundColor:style.backgroundColor,fontWeight:style.fontWeight,fontStyle:style.fontStyle,textDecoration:style.textDecoration,textAlign:style.textAlign};for(const a of [...child.attributes])child.removeAttribute(a.name);for(const [k,v]of Object.entries(safe))if(v)child.style[k]=v;if(color&&/^#[0-9a-f]{3,8}$/i.test(color))child.style.color=color;walk(child);}};walk(template.content);return template.innerHTML;}
function richCommand(command){const n=current();if(!n)return;if(n.language!=='rich'){snapshot();n.language='rich';n.rich=esc(n.content).replace(/\n/g,'<br>');loadEditor();toast('Rich text enabled. Select text to format.');}$('#richEditor').focus();document.execCommand(command,false,null);changed();}
function insertText(text){const n=current();if(!n)return;if(n.language==='rich'){$('#richEditor').focus();document.execCommand('insertText',false,text);changed();}else{const el=$('#editor');el.focus();el.setRangeText(text,el.selectionStart,el.selectionEnd,'end');changed();} }
function openModal(title,html){$('#modalTitle').textContent=title;$('#modalBody').innerHTML=html;$('#modal').showModal();}
const closeModal=()=>$('#modal').close();
function download(name,content,type='text/plain;charset=utf-8'){const blob=new Blob([content],{type});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=name.replace(/[\\/:*?"<>|]/g,'_');a.click();setTimeout(()=>URL.revokeObjectURL(url),10000);}
function exportDialog(){const n=current();if(!n)return toast('Open a note to download it.');openModal('Download your note',`<p class="hint">A local file, ready immediately. No upload or conversion server.</p><div class="form-row"><label for="fileName">File name</label><input id="fileName" value="${esc(n.title||'Untitled note')}.${extensions[n.language]}"></div><div class="form-row"><label for="exportFormat">Content</label><select id="exportFormat"><option value="text">Plain text / source code</option><option value="html" ${n.language==='rich'?'selected':''}>Formatted HTML</option></select></div><p class="hint">Use any text-based extension: .txt, .sql, .md, .json, .csv, .py, and more. Changing an extension does not convert file contents.</p><div class="modal-actions"><button id="printInstead">Print / PDF</button><button class="primary" id="confirmDownload">Download file</button></div>`);$('#confirmDownload').onclick=()=>{const html=$('#exportFormat').value==='html';download($('#fileName').value||'note.txt',html?`<!doctype html><html><head><meta charset="utf-8"><title>${esc(n.title)}</title></head><body><h1>${esc(n.title)}</h1><div style="white-space:pre-wrap;font-family:${n.font==='serif'?'serif':'sans-serif'};font-size:${n.size}px;color:${n.textColor}">${n.language==='rich'?sanitize(n.rich):esc(n.content)}</div></body></html>`:n.content,html?'text/html;charset=utf-8':undefined);closeModal();toast('File downloaded');};$('#exportFormat').onchange=()=>{$('#fileName').value=($('#fileName').value.replace(/\.[^.]+$/,''))+($('#exportFormat').value==='html'?'.html':'.txt');};$('#printInstead').onclick=()=>{closeModal();printNote();};}
function printNote(){const n=current();if(!n)return;$('#printArea').innerHTML=`<h1>${esc(n.title)}</h1><div>${n.language==='rich'?sanitize(n.rich):esc(n.content)}</div>`;window.print();}
function backup(){save();download('online-notepad-backup-'+new Date().toISOString().slice(0,10)+'.notepad',JSON.stringify({...state,exportedAt:new Date().toISOString()},null,2),'application/json');toast('Workspace backup downloaded');}
function updateFindCount(){const n=current();if(!n)return;const q=$('#findInput').value;let hay=n.content;if(!$('#matchCase').checked){hay=hay.toLowerCase();}const needle=$('#matchCase').checked?q:q.toLowerCase();$('#findCount').textContent=q?`${hay.split(needle).length-1} matches`:'';}
function showFind(){$('#findBar').hidden=false;$('#findInput').focus();updateFindCount();}
function findNext(){const n=current();if(!n)return;const q=$('#findInput').value;if(!q)return;if(n.language==='rich'){toast('Switch to Plain text to select or replace a match.');return;}const e=$('#editor'),hay=$('#matchCase').checked?n.content:n.content.toLowerCase(),needle=$('#matchCase').checked?q:q.toLowerCase();let at=hay.indexOf(needle,e.selectionEnd);if(at<0)at=hay.indexOf(needle);if(at<0)return toast('No matches found');e.focus();e.setSelectionRange(at,at+q.length);const line=n.content.slice(0,at).split('\n').length;e.scrollTop=Math.max(0,(line-3)*n.size*1.8);syncScroll();stats();}
function replace(all){const n=current();if(!n)return;if(n.language==='rich')return toast('Switch to Plain text before replacing text.');const q=$('#findInput').value;if(!q)return;const e=$('#editor');if(all){const re=new RegExp(q.replace(/[.*+?^${}()|[\]\\]/g,'\\$&'),$('#matchCase').checked?'g':'gi');e.value=e.value.replace(re,()=>$('#replaceInput').value);changed();}else{const selected=e.value.slice(e.selectionStart,e.selectionEnd);if(($('#matchCase').checked?selected:selected.toLowerCase())===($('#matchCase').checked?q:q.toLowerCase())){e.setRangeText($('#replaceInput').value,e.selectionStart,e.selectionEnd,'end');changed();}findNext();}updateFindCount();}
function noteActions(){const n=current();if(!n)return;openModal('Make it yours',`<div class="hint">Note color</div><div class="swatches">${Object.entries(colors).map(([k,c])=>`<button data-color="${k}" style="background:${c[0]}" aria-label="${k} note"></button>`).join('')}</div><div class="tool-grid"><button id="duplicate">▤ Duplicate note</button><button id="printNote">▧ Print / PDF</button><button id="copyNote">⧉ Copy all text</button><button id="deleteNote" class="danger">♲ Move to trash</button></div><p class="hint">Created ${new Date(n.created).toLocaleString()}<br>Last edited ${new Date(n.updated).toLocaleString()}</p>`);$$('[data-color]').forEach(b=>b.onclick=()=>{n.color=b.dataset.color;save();loadEditor();render();closeModal();});$('#duplicate').onclick=()=>{const copy={...n,id:uid(),title:n.title+' (copy)',created:Date.now(),updated:Date.now(),x:n.x+25,y:n.y+25};state.notes.unshift(copy);closeModal();choose(copy.id);};$('#deleteNote').onclick=()=>{n.deleted=true;n.updated=Date.now();state.active=state.notes.find(x=>!x.deleted)?.id;save();closeModal();loadEditor();render();toast('Moved to trash. You can restore it anytime.');};$('#printNote').onclick=()=>{closeModal();printNote();};$('#copyNote').onclick=()=>copyText(n.content);}
async function copyText(text){try{await navigator.clipboard.writeText(text);toast('Copied to clipboard');}catch{const el=document.createElement('textarea');el.value=text;document.body.append(el);el.select();const success=document.execCommand('copy');el.remove();toast(success?'Copied to clipboard':'Use Ctrl/Cmd+A then Ctrl/Cmd+C in the editor.');}}
function showTrash(n){openModal(n.title,`<p class="hint">Restore this note to your workspace or delete it permanently.</p><div class="modal-actions"><button id="purge" class="danger">Delete forever</button><button id="restore" class="primary">Restore note</button></div>`);$('#restore').onclick=()=>{n.deleted=false;save();closeModal();render();toast('Note restored');};$('#purge').onclick=()=>{openModal('Permanently delete this note?',`<p class="hint">“${esc(n.title)}” cannot be recovered after deletion.</p><div class="modal-actions"><button id="cancelDelete">Cancel</button><button id="confirmDelete" class="danger">Delete forever</button></div>`);$('#cancelDelete').onclick=closeModal;$('#confirmDelete').onclick=()=>{state.notes=state.notes.filter(x=>x.id!==n.id);save();closeModal();render();};};}
function toolsDialog(){openModal('Editing tools',`<div class="tool-grid"><button data-tool="date">Insert date & time</button><button data-tool="symbols">Symbols & emoji</button><button data-tool="upper">UPPERCASE selection</button><button data-tool="lower">lowercase selection</button><button data-tool="sort">Sort selected lines</button><button data-tool="dedupe">Remove duplicate lines</button><button data-tool="json">Format JSON</button><button data-tool="trim">Trim trailing spaces</button><button data-tool="copy">Copy all</button><button data-tool="select">Select all</button><button data-tool="cut">Cut selection</button><button data-tool="paste">Paste text</button></div><p class="hint">For selected-text tools, select text before opening this menu. With no selection, the tool applies to the whole note.</p>`);$$('[data-tool]').forEach(b=>b.onclick=()=>{const action=b.dataset.tool;closeModal();const n=current();if(!n)return;if(action==='date')return insertText(new Date().toLocaleString());if(action==='symbols')return symbols();if(action==='copy')return copyText(n.content);if(action==='select'){if(n.language==='rich'){$('#richEditor').focus();document.execCommand('selectAll');}else{$('#editor').focus();$('#editor').select();}return;}if(action==='paste'){navigator.clipboard?.readText().then(insertText).catch(()=>toast('Use Ctrl/Cmd+V to paste in the editor.'));return;}if(n.language==='rich')return toast('Switch to Plain text or code mode for this tool.');const el=$('#editor'),a=el.selectionStart,b=el.selectionEnd,selection=a!==b;let text=selection?el.value.slice(a,b):el.value;if(action==='cut'){if(!selection)return toast('Select text to cut first.');copyText(text);el.setRangeText('',a,b,'end');changed();return;}try{text=action==='upper'?text.toUpperCase():action==='lower'?text.toLowerCase():action==='sort'?text.split('\n').sort().join('\n'):action==='dedupe'?[...new Set(text.split('\n'))].join('\n'):action==='json'?JSON.stringify(JSON.parse(text),null,2):text.replace(/[\t ]+$/gm,'');}catch{return toast('This text is not valid JSON. No changes made.');}if(selection)el.setRangeText(text,a,b,'select');else el.value=text;changed();});}
function symbols(){openModal('Symbols & emoji',`<div class="symbol-grid">${['✓','☐','☑','✗','•','→','←','↑','↓','↔','₹','$','€','£','©','®','™','°','±','×','÷','∞','≈','≠','≤','≥','α','β','π','Σ','Ω','µ','😀','😊','🎯','💡','⭐','✨','📌','📝','🚀','✅','❤️','🎉','🔥','👍','🙏','💬'].map(c=>`<button>${c}</button>`).join('')}</div>`);$$('.symbol-grid button').forEach(b=>b.onclick=()=>{const t=b.textContent;closeModal();insertText(t);});}
function preferences(){openModal('Your workspace, your way',`<div class="form-row"><label for="motion">Ambient motion<small>Floating background, card transitions, and typing glow.</small></label><input id="motion" type="checkbox" ${state.settings.motion?'checked':''}></div><div class="form-row"><label for="spellcheck">Browser spellcheck<small>For plain and rich text. Offline dictionaries depend on your browser.</small></label><input id="spellcheck" type="checkbox" ${state.settings.spellcheck?'checked':''}></div><div class="form-row"><label for="background">Background</label><select id="background"><option value="dots">Blue mist</option><option value="white">Clean white</option><option value="grid">Dot grid</option></select></div><div class="form-row"><span>Browser storage used</span><span>${(new Blob([JSON.stringify(state)]).size/1024).toFixed(1)} KB</span></div><p class="hint">Notes stay in this browser profile. Clearing site data removes them. Keep a downloaded workspace backup. Notes are not synced between devices.</p><div class="form-row"><span>New note</span><kbd>Ctrl/⌘ + Alt + N</kbd></div><div class="form-row"><span>Download note</span><kbd>Ctrl/⌘ + S</kbd></div><div class="form-row"><span>Find & replace</span><kbd>Ctrl/⌘ + F</kbd></div><div class="form-row"><span>Undo / redo</span><kbd>Ctrl/⌘ + Z / Shift + Z</kbd></div><div class="form-row"><span>Insert date / indent code</span><kbd>F5 / Tab</kbd></div><div class="modal-actions"><button id="zipSettings">Export all as ZIP</button><button id="backupSettings">Download backup</button><button class="primary" id="doneSettings">Done</button></div>`);$('#background').value=state.settings.background;for(const k of ['motion','spellcheck','background'])$('#'+k).onchange=e=>{state.settings[k]=k==='background'?e.target.value:e.target.checked;save();applyEditorSettings();applyBackground();};$('#zipSettings').onclick=exportZip;$('#backupSettings').onclick=backup;$('#doneSettings').onclick=closeModal;}
function applyBackground(){document.body.style.background=state.settings.background==='white'?'#fff':state.settings.background==='grid'?'radial-gradient(#cbd6ee 1px, transparent 1px) 0 0 / 22px 22px #f7f9fd':'#f5f7fc';}
function setupDrag(){$$('.note-card .card-top').forEach(handle=>handle.onpointerdown=e=>{if(e.target.closest('button'))return;const card=handle.closest('.note-card'),n=state.notes.find(n=>n.id===card.dataset.id),startX=e.clientX,startY=e.clientY,x=n.x,y=n.y;handle.setPointerCapture(e.pointerId);card.style.zIndex='5';handle.onpointermove=ev=>{n.x=Math.max(0,Math.min(1800,x+(ev.clientX-startX)/zoom));n.y=Math.max(0,Math.min(1200,y+(ev.clientY-startY)/zoom));card.style.left=n.x+'px';card.style.top=n.y+'px';};handle.onpointerup=()=>{handle.onpointermove=null;card.style.zIndex='';save();};handle.onpointercancel=()=>{handle.onpointermove=null;save();};});$$('.note-card').forEach(card=>card.onpointerup=()=>{const n=state.notes.find(n=>n.id===card.dataset.id);n.width=card.offsetWidth;n.height=card.offsetHeight;scheduleSave();});}
function inferLanguage(name){const ext=name.split('.').pop().toLowerCase();return({txt:'plain',md:'markdown',sql:'sql',js:'javascript',ts:'typescript',py:'python',json:'json',html:'html',htm:'html',xml:'html',css:'css',sh:'shell'})[ext]||'plain';}
function validateNote(n){if(!n||typeof n.title!=='string'||typeof n.content!=='string'||n.content.length>5e6)throw Error('Invalid note in backup');const base=makeNote(n.title,n.content,extensions[n.language]?n.language:'plain',colors[n.color]?n.color:'blue');return{...base,pinned:!!n.pinned,deleted:!!n.deleted,font:fonts[n.font]?n.font:base.font,size:[14,16,18,20,24,28,32].includes(n.size)?n.size:16,textColor:/^#[0-9a-f]{6}$/i.test(n.textColor)?n.textColor:base.textColor,rich:typeof n.rich==='string'?sanitize(n.rich):'',created:Number.isFinite(n.created)?n.created:base.created,updated:Number.isFinite(n.updated)?n.updated:base.updated,x:Number.isFinite(n.x)?Math.max(0,Math.min(n.x,1800)):base.x,y:Number.isFinite(n.y)?Math.max(0,Math.min(n.y,1200)):base.y,width:Number.isFinite(n.width)?Math.max(220,Math.min(n.width,1000)):270,height:Number.isFinite(n.height)?Math.max(220,Math.min(n.height,1000)):245};}
async function importFiles(files){let count=0;for(const file of files){try{if(file.size>5*1024*1024)throw Error('File exceeds the 5 MB text limit');if(/^(image|audio|video)\//.test(file.type)||!/\.(txt|md|sql|js|ts|py|json|html?|xml|css|csv|tsv|log|ya?ml|sh|ini|conf|rtf|java|c|cpp|h|rb|php|toml|notepad)$/i.test(file.name))throw Error('Only text and code files are supported');const buf=await file.arrayBuffer();if(new Uint8Array(buf).includes(0))throw Error('Binary files are not supported');const text=new TextDecoder('utf-8',{fatal:true}).decode(buf);if(file.name.endsWith('.notepad')){const data=JSON.parse(text);if(data.version!==1||!Array.isArray(data.notes)||data.notes.length>3000)throw Error('Invalid workspace backup');const notes=data.notes.map(validateNote);state.notes.push(...notes);count+=notes.length;if(notes.find(n=>!n.deleted))state.active=notes.find(n=>!n.deleted).id;}else{const n=makeNote(file.name.replace(/\.[^.]+$/,''),text,inferLanguage(file.name));state.notes.unshift(n);state.active=n.id;count++;}}catch(e){toast(`${file.name}: ${e.message}`);}}if(count){save();filter='all';setFilter('all');setView('editor');render();toast(`Imported ${count} ${count===1?'note':'notes'}. Existing notes preserved.`);}$('#fileInput').value='';}
$('#newNote').onclick=newNote;$('.brand').onclick=e=>{e.preventDefault();setFilter('all');};$('#noteList').onclick=e=>{const b=e.target.closest('[data-note]');if(b)choose(b.dataset.note);};$$('[data-filter]').forEach(b=>b.onclick=()=>setFilter(b.dataset.filter));$$('[data-view]').forEach(b=>b.onclick=()=>setView(b.dataset.view));$('#search').oninput=()=>{renderList();if($('#search').value)setView('board');else if(view!=='editor')renderBoard();};$('#sort').onchange=renderBoard;
$('#title').oninput=()=>{const n=current();if(!n)return;n.title=$('#title').value;n.updated=Date.now();scheduleSave();renderList();};$('#editor').oninput=changed;$('#richEditor').oninput=changed;$('#editor').onscroll=syncScroll;$('#editor').onselect=stats;$('#editor').onclick=stats;$('#editor').onkeyup=stats;$('#editor').onblur=renderList;
$('#richEditor').onpaste=e=>{e.preventDefault();insertText(e.clipboardData.getData('text/plain'));};$('#richEditor').ondrop=e=>{e.preventDefault();toast('Import text files using Import files. Images are not supported.');};$('#richEditor').addEventListener('beforeinput',e=>{if(e.inputType==='insertFromDrop')e.preventDefault();});
$('#language').onchange=()=>{const n=current();if(!n)return;const lang=$('#language').value;if(n.language==='rich'&&lang!=='rich'){if(!confirm('Switching to plain text or code removes rich text formatting. Continue?')){$('#language').value='rich';return;}n.rich='';}n.language=lang;n.font=['plain','rich'].includes(lang)?'sans':'mono';save();loadEditor();renderList();};for(const [id,key]of [['font','font'],['fontSize','size']])$('#'+id).onchange=e=>{const n=current();if(!n)return;n[key]=key==='size'?Number(e.target.value):e.target.value;applyEditorSettings();save();};$('#textColor').oninput=e=>{const n=current();if(!n)return;n.textColor=e.target.value;applyEditorSettings();save();};$$('[data-command]').forEach(b=>{b.onmousedown=e=>e.preventDefault();b.onclick=()=>richCommand(b.dataset.command);});
$('#pinNote').onclick=()=>{const n=current();if(!n)return;n.pinned=!n.pinned;save();loadEditor();render();};$('#expandNote').onclick=()=>document.body.classList.toggle('expanded');$('#sidebarToggle').onclick=()=>document.body.classList.toggle('hide-sidebar');$('#noteMenu').onclick=noteActions;$('#toolsButton').onclick=toolsDialog;$('#downloadCurrent').onclick=exportDialog;$('#backupButton').onclick=backup;$('#settingsButton').onclick=preferences;$('#importButton').onclick=()=>$('#fileInput').click();$('#fileInput').onchange=e=>importFiles([...e.target.files]);$('#closeModal').onclick=closeModal;$('#modal').onclick=e=>{if(e.target===$('#modal'))closeModal();};$('#undo').onclick=()=>historyMove();$('#redo').onclick=()=>historyMove(true);$('#wrapButton').onclick=()=>{state.settings.wrap=!state.settings.wrap;applyEditorSettings();save();};$('#findButton').onclick=showFind;$('#closeFind').onclick=()=>$('#findBar').hidden=true;$('#findInput').oninput=updateFindCount;$('#matchCase').onchange=updateFindCount;$('#findNext').onclick=findNext;$('#replaceOne').onclick=()=>replace(false);$('#replaceAll').onclick=()=>replace(true);$('#findInput').onkeydown=e=>{if(e.key==='Enter'){e.preventDefault();findNext();}};
$('#board').onclick=e=>{const p=e.target.closest('[data-pin]'),o=e.target.closest('[data-open]');if(p){const n=state.notes.find(n=>n.id===p.dataset.pin);n.pinned=!n.pinned;save();render();}if(o)choose(o.dataset.open);};$('#board').ondblclick=e=>{const card=e.target.closest('.note-card');if(card)choose(card.dataset.id);};function setZoom(z){zoom=Math.max(.5,Math.min(1.5,z));$('#board').style.transform=`scale(${zoom})`;$('#zoomLevel').textContent=Math.round(zoom*100)+'%';}$('#zoomIn').onclick=()=>setZoom(zoom+.1);$('#zoomOut').onclick=()=>setZoom(zoom-.1);$('#resetCanvas').onclick=()=>{setZoom(1);$('#boardViewport').scrollTo(0,0);};
$('#editor').onkeydown=e=>{if(e.key==='Tab'){e.preventDefault();insertText('    ');}if(e.key==='F5'){e.preventDefault();insertText(new Date().toLocaleString());}};
document.addEventListener('keydown',e=>{const mod=e.ctrlKey||e.metaKey;if($('#modal').open)return;if(mod&&e.altKey&&e.key.toLowerCase()==='n'){e.preventDefault();newNote();}if(mod&&e.key.toLowerCase()==='s'){e.preventDefault();exportDialog();}if(mod&&e.key.toLowerCase()==='f'&&view==='editor'){e.preventDefault();showFind();}if(mod&&e.key.toLowerCase()==='z'&&e.target!==$('#title')){e.preventDefault();historyMove(e.shiftKey);}if(mod&&e.key.toLowerCase()==='y'){e.preventDefault();historyMove(true);}if(e.key==='Escape'){$('#findBar').hidden=true;document.body.classList.remove('expanded');}});
window.addEventListener('pagehide',save);document.addEventListener('visibilitychange',()=>{if(document.hidden)save();});window.addEventListener('storage',e=>{if(e.key===KEY&&e.newValue){try{const incoming=JSON.parse(e.newValue);if(Array.isArray(incoming.notes)&&incoming.settings){clearTimeout(saveTimer);state=incoming;loadEditor();render();toast('Workspace updated from another tab');}}catch{}}});
$('#newNote kbd').textContent='⌘ ⌥ N';applyBackground();loadEditor();render();if(storageOK)save();
if('serviceWorker' in navigator&&location.protocol!=='file:'){navigator.serviceWorker.register('./sw.js').then(async()=>{await navigator.serviceWorker.ready;$('#offlineStatus').textContent='▣ Ready for offline use';}).catch(()=>{$('#offlineStatus').textContent='▣ Local storage · offline cache unavailable';});}else{$('#offlineStatus').textContent='▣ Offline file · stored in this browser';}

// Uncompressed ZIP export: no runtime dependency, no network, UTF-8 filenames.
function exportZip(){
 const encoder=new TextEncoder(),parts=[],central=[];let offset=0;
 const table=Array.from({length:256},(_,i)=>{let c=i;for(let k=0;k<8;k++)c=(c&1)?0xedb88320^(c>>>1):c>>>1;return c>>>0;});
 const crc32=data=>{let c=0xffffffff;for(const b of data)c=table[(c^b)&255]^(c>>>8);return(c^0xffffffff)>>>0;};
 const used=new Set();const notes=state.notes.filter(n=>!n.deleted);
 for(const n of notes){let base=(n.title||'Untitled note').replace(/[\\/:*?"<>|]/g,'_'),ext=extensions[n.language]||'txt',name=base+'.'+ext,i=2;while(used.has(name))name=base+' ('+(i++)+').'+ext;used.add(name);const filename=encoder.encode(name),data=encoder.encode(n.language==='rich'?'<!doctype html><meta charset="utf-8"><title>'+esc(n.title)+'</title>'+sanitize(n.rich):n.content),crc=crc32(data);
 const header=new Uint8Array(30+filename.length),v=new DataView(header.buffer);v.setUint32(0,0x04034b50,true);v.setUint16(4,20,true);v.setUint16(6,0x800,true);v.setUint32(14,crc,true);v.setUint32(18,data.length,true);v.setUint32(22,data.length,true);v.setUint16(26,filename.length,true);header.set(filename,30);parts.push(header,data);
 const entry=new Uint8Array(46+filename.length),e=new DataView(entry.buffer);e.setUint32(0,0x02014b50,true);e.setUint16(4,20,true);e.setUint16(6,20,true);e.setUint16(8,0x800,true);e.setUint32(16,crc,true);e.setUint32(20,data.length,true);e.setUint32(24,data.length,true);e.setUint16(28,filename.length,true);e.setUint32(42,offset,true);entry.set(filename,46);central.push(entry);offset+=header.length+data.length;
 }
 const end=new Uint8Array(22),v=new DataView(end.buffer);v.setUint32(0,0x06054b50,true);v.setUint16(8,notes.length,true);v.setUint16(10,notes.length,true);v.setUint32(12,central.reduce((s,a)=>s+a.length,0),true);v.setUint32(16,offset,true);const blob=new Blob([...parts,...central,end],{type:'application/zip'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='online-notepad-notes.zip';a.click();setTimeout(()=>URL.revokeObjectURL(url),10000);toast('All active notes exported as ZIP');
}
